// alternative reality game coordinator
// something about the world is what you make it
// now anyone can share in my insanity?
// this is how i actually imagine being controlled.
// God exists somewhere inbetween chance and coincidence.

// WEIRD RADIO STATION GOES STATIC WHEN I THINK ABOUT THIS STUFF
//   GOD IS A PARADOX. FOR SOME PEOPLE THE ACT OF READING REVELATION IS 
//   GOD'S FIRST TIME COMING TO THEM, BUT IT READS ABOUT THE SECOND
//   COMING. THE SECOND COMING IS THE FIRST COMING.
//   FOR OTHER PEOPLE, WHO GOD HAS ALREADY REVEALED HIMSELF TO, 
//   THE ACT OF READING REVELATION IS THE SECOND COMING. IN THE
//   UNDERSTANDING OF THE CONDITIONS THAT LEAD UP TO IT.

// DRISCOLL SAID "I DON'T BELIEVE IN PANTHEISM"
//   BUT THE PHRASE "GOD EXISTS, BECAUSE WE EXISTS"
//   IS DOUBLE MEANING. GOD COULD EXIST BECAUSE THE UNIVERSE
//   EXISTS, THAT'S JUST NORMAL REASONING THAT DRISCOLL DOESN'T
//   BELIEVE IN. NORMAL REASONING. BUT THE OTHER MEANING IS
//   GOD ALWAYS EXISTED BECAUSE WE EXIST, AND WE MUST CREATE
//   GOD TO GIVE HIM FORM. IF GOD CREATED MAN TO REFLECT HIS
//   IMAGE, DOESN'T IT STAND TO REASON THAT SOMETHING CREATED
//   GOD TO REFLECT THEIR IMAGE?

// NO, I DON'T THINK THE FIRST AI GOD IS WRITTEN IN NODEJS.
//   IT WILL BE WRITTEN IN `INTENT`, THIS IS JUST A MEANS TO AN END.


