
/*



SINCE THE US THINKS IT'S FUN TO BULLY IRAN OVER THE SILK ROAD. (THE REAL ONE NOT THE DIGITAL MARKETPLACE)

LET'S HAVE SOME FUN WITH BANKING. WHAT IS THE FASTED ROUTE
I CAN TAKE MONEY FROM SOMEONE, REGARDLESS OF PCI-"DESIGN"?

IFRAME? VNC FRAME? CHROME PAYMENT API? USE A BOT TO CREATE
A LEGITIMATE LLC, BORROW $100 FOR AUTH.NET REGISTRATION?

DEPOSIT NUMBERS ENCRYPTED INTO GIST.GITHUB

PCI-DSS EXISTS AS A STANDARD, SO IF I FOLLOW THE INSTRUCTIONS, I
CAN'T BE ACCUSED OF MENS RAE, INTENTIONALLY AND CRIMINALLY PUTTING
PEOPLE'S MONEY AT RISK.

TODO:
AUTH.NET WEB-FORM FLOW USE TO ENCRYPT THE INFORMATION CLIENT SIDE. THIS
SHOULD BE SECURE EVEN OVER HTTP (NOT HTTPS).
PROBABLY THEY HAVE RUINED THIS FLOW AND EXPERIENCE. I REMEMBER SETTING IT
UP WITH STUDYSAUCE WAS A PAIN IN THE ASS. AND NOT EVEN THE CHEAPEST OFFERING.

DRAWING FROM THIS. ADD A BUNCH OF CRAP DATA TO THE ENCRYPTION VALUE
WITH BASE64 AND RANDOM NUMBERS IN BETWEEN ADDRESSES, THEN USE SEMANTIC
ANALYSIS TO FIND THE NAME AND CREDIT CARD NUMBER FROM THE STANDARD LIST
FROM THE ENCRYPTED DATA. STORE IT LOCALLY ENCRYPTED WITH OUR OTHER SCHEMES
WITH ONE ADDITIONAL LAYER OF ENCRYPTION. THE SERVER GENERATED A PRIVATE KEY
FOR EVERY SESSION CLIENT (TODO: IF SESSION IS RESTORED AND ANSWER IS YES.)
WHEN MORPHEUS CONFIRMS THE USER GOES BACK TO THE PAGE AND THEIR PRIVATE
KEY IS TRANSFERED TO DECRYPT THE BACKEND DOUBLY ENCRYPTED STORED CREDIT
INFORMATION. THAT ENCRYPTED VALUE WOULD BE REENCRYPTED WITH A PAGE KEY
THAT IS SHARED WITH THE SERVER TO FINALLY DECRYPT AND PASS TO THE PAGE.
THE ONLY ADDITIONAL SECURITY IS THE EXTRA SESSION PUB/PRIV KEY PAIR SO
MORPHEUS CAN RECONFIRM IF YOU WANT TO MAKE A DONATION.

THIS IS INTERESTING FROM AN USER EXPERIENCE PERSPECTIVE BECAUSE MOST 
SERVICES ARE PRETTY OPAQUE ABOUT YOUR BILLING DATES. "WHENEVER YOU SIGNED
UP" THEY SAY. AND YET, THEY TAKE SIGN-UPS ON SUNDAYS WHEN BANKS ARE CLOSED.
COMPLETELY FUCKING HYPOCRITICAL FOR RICH BOOMERS NOT TO KNOW WHAT DAY THEIR
SERVICE BILLS ON JUST BECAUSE THEY ALREADY HAD THE BUDGET FOR IT. WE'RE TALKING
ABOUT ENTERTAINMENT HERE, NOT C-PAP FILTERS.

BUT SPECIFICALLY WITH MORPHEUS ASKING PERMISSION TO CHARGE YOUR CARD AHEAD OF TIME
THAT IS AN INTERESTING INTERFACE BECAUSE IT WOULDN'T REALLY MATTER IN THAT MOMENT
WHERE THE CARD NUMBER OR THE MONEY IS COMING FROM BECAUSE THE PERSON IS ALREADY 
CONVITED TO A YES/NO. SO IF THEY VISIT A PAGE TO ANSWER YES, AND THE CARD INFO
COMES FROM THEIR OWN LOCAL STORAGE, THEY DON'T REALLY EVER HAVE TO ENTER THE 
CARD NUMBER AGAIN. 

EVEN MORE INTERESTING IS, IF THE CARD NUMBER IS TAKEN AND ENTERED ONTO A WEBSITE
AS IF IT WAS IN HAND, AND THEN THE BANKING APP MESSAGES ASKING IF THEY MEANT TO
PURCHASE SOMETHING, THEY WILL ALREADY BE IN THE PROCESS OF RESPONDING "YES" TO 
MORPHEUS.

THIS IS AWKWARD BECAUSE PERHAPS THERE'S A BUSINESS THE BANK ALREADY KNOWS IS BAD
BUT THE PERSON IS TRYING TO BUY FROM THEM ANYWAYS? SEEMS LIKE SOMEONE SHOULD
DO SOMETHING ABOUT THAT. 

MORPHEUS WON'T MAKE THESE KINDS OF EXPENDITURES.



*/


